#ifndef MEMORY_MAP__HEADER
#define MEMORY_MAP__HEADER

#include <stdint.h>

// THIS IS STILL TEMPORARY

/* SERIAL PORT */
#define SERIAL_INPUT_ADDRESS_LO 0x78000
#define SERIAL_INPUT_ADDRESS_HI 0x79fff

#define SERIAL_OUTPUT_ADDRESS_LO 0x7a000
#define SERIAL_OUTPUT_ADDRESS_HI 0x7bfff

#define SERIAL_STATUS_TXE_LO 0x7D000
#define SERIAL_STATUS_TXE_HI 0x7DFFF

#define SERIAL_STATUS_RDF_LO 0x7c000
#define SERIAL_STATUS_RDF_HI 0x7cfff

#define MAX_ROM 0x0  // no ROM
#define MAX_RAM 0xffffff

#endif